# Generated by Django 4.1.2 on 2022-10-05 19:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('1', 'Débito+'), ('2', 'Boleto-'), ('3', 'Financiamento-'), ('4', 'Crédito+'), ('5', 'Recebimento Empréstimo+'), ('6', 'Vendas+'), ('7', 'Recebimento TED+'), ('8', 'Recebimento DOC+'), ('9', 'Aluguel-')], max_length=1)),
                ('value', models.CharField(max_length=10)),
                ('CPF', models.CharField(max_length=11)),
                ('card', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='companies.company')),
            ],
        ),
    ]
